package com.github.maximebonnet27;

public enum Biomes {

  OCEAN, DEEP_OCEAN, SUBTROPICAL_DESERT, TEMPERATE_DESERT, GRASSLAND, TROPICAL_SEASONAL_FOREST,
  TROPICAL_RAIN_FOREST, TEMPERATE_RAIN_FOREST, TEMPERATE_DECIDUOUS_FOREST, TAIGA, SHRUBLAND,
  SCORCHED, BARE, TUNDRA, SNOW
  
}